In [1]:
import numpy as np

a = np.random.randn(5)

In [2]:
print(a)

[-1.19144898 -0.51394302  0.11130928 -0.40686052 -1.98509458]


In [3]:
np.shape(a)

(5,)

In [4]:
print(a.T)

[-1.19144898 -0.51394302  0.11130928 -0.40686052 -1.98509458]


In [5]:
print(np.dot(a, a.T))

5.802213815747456


In [6]:
a = np.random.randn(5,1)

In [7]:
print(a)

[[-0.18482361]
 [-0.33798277]
 [-0.46285695]
 [-0.124519  ]
 [-1.99383405]]


In [8]:
print(a.T)

[[-0.18482361 -0.33798277 -0.46285695 -0.124519   -1.99383405]]


In [9]:
print(np.dot(a, a.T))

[[0.03415977 0.06246719 0.08554689 0.02301405 0.3685076 ]
 [0.06246719 0.11423235 0.15643767 0.04208528 0.67388156]
 [0.08554689 0.15643767 0.21423656 0.05763449 0.92285995]
 [0.02301405 0.04208528 0.05763449 0.01550498 0.24827023]
 [0.3685076  0.67388156 0.92285995 0.24827023 3.97537424]]


In [10]:
np.shape(a)

(5, 1)

In [14]:
assert(a.shape == (5,1))

In [15]:
a = np.random.randn(2, 3) # a.shape = (2, 3)
b = np.random.randn(2, 1) # b.shape = (2, 1)
c = a + b

In [17]:
c.shape

(2, 3)

In [18]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [19]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)

In [20]:
c.shape

(12288, 45)

In [21]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b


In [22]:
c.shape

(3, 3)

In [26]:
a = np.random.randn(3,4)
b = np.random.randn(4,1)

for i in range(3):
    for j in range(4):
        c[i][j] = a[i][j] + b[j]
    
print(c)    

IndexError: index 3 is out of bounds for axis 0 with size 3